---
name: Lint OpenAPI Descriptions

on:
  - push

jobs:
  build:
    name: Lint OpenAPI Descriptions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Yaml Lint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: 'descriptions/**/*.yaml'
          yamllint_strict: false
          yamllint_config_datapath: '---\n:extends: relaxed\n:rules:\n  :line-length: disabled\n  :trailing-spaces: disabled\n'
          yamllint_comment: true
      - name: OpenAPI Lint
        uses: mattpage/redocly-cli-lint-action@v0.0.1
        with:
          entrypoints: 'descriptions/**/*.yaml'
          config: '.redocly.yml'
