---
name: Lint OpenAPI Descriptions

on:
  - push

jobs:
  build:
    name: Lint OpenAPI Descriptions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Yaml Lint
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout'
            uses: actions/checkout@master
          - name: 'Yamllint'
            uses: karancode/yamllint-github-action@master
            with:
              yamllint_file_or_dir: 'descriptions/**/*.yaml'
              yamllint_strict: false
              yamllint_comment: true
            env:
              GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: OpenAPI Lint
        uses: mattpage/redocly-cli-lint-action@v0.0.1
        with:
          entrypoints: 'descriptions/**/*.yaml'
          config: '.redocly.yml'
