---
name: Lint YAML and OpenAPI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_OPENAPI: true
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: /
          OPENAPI_FILE_NAME: .spectral.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
