---
name: Lint OpenAPI Descriptions

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint YAML & JSON
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Spectral OpenAPI Schema Check
        uses: stoplightio/spectral-action@v0.5.5
        with:
          file_glob: descriptions/**/*.yaml
        env:
          INPUT_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
