name: Spectral OpenAPI Schema Check
on:
  - push
jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stoplightio/spectral-action@v0.5.5
        with:
          file_glob: descriptions/**/*.yaml
